# Generated by Django 5.2.8 on 2025-11-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pq_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If true, participants can join with just the session code (no password).'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='join_password',
            field=models.CharField(blank=True, help_text='Optional password/key set by host. Leave empty for public sessions.', max_length=128),
        ),
    ]
