# Generated by Django 5.2.8 on 2025-12-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pq_test', '0003_quiz_total_time_and_session_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerrecord',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pq_test.question'),
        ),
    ]
