# Generated by Django 5.2.8 on 2025-12-10 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pq_test', '0004_alter_answerrecord_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsession',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='pq_test.quiz'),
        ),
    ]
