# Generated by Django 5.2.8 on 2025-12-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0002_footercolumn_heroslide_productsection_promoconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circlecategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload circle icon image (or use external URL).', null=True, upload_to='circle_categories/'),
        ),
        migrations.AddField(
            model_name='heroitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload hero item image (or use external URL).', null=True, upload_to='hero_items/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload product image (or use external image URL below).', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='circlecategory',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
