# Generated by Django 5.2.8 on 2025-12-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0003_circlecategory_image_heroitem_image_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsection',
            name='auto_fill',
            field=models.BooleanField(default=False, help_text='If enabled, this row will automatically show latest active products.'),
        ),
        migrations.AddField(
            model_name='productsection',
            name='max_products',
            field=models.PositiveIntegerField(default=12, help_text='Maximum number of products to display when auto_fill is on.'),
        ),
    ]
