# Generated by Django 5.2.8 on 2025-11-20 11:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0002_remove_page_access_levels_page_access_level_and_more'),
        ('navigation', '0002_remove_menuitem_access_levels_menuitem_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.CharField(choices=[('owner', 'Owner & Super Administrator'), ('developer', 'Developer / Programmer'), ('admin', 'Administrator'), ('chapter_head', 'Head of Local Chapter'), ('member', 'End User / Member'), ('visitor', 'Visitor'), ('pee_member', 'Private Equity Exchange Member')], default='visitor', max_length=32),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('owner', 'Owner & Super Administrator'), ('developer', 'Developer / Programmer'), ('admin', 'Administrator'), ('chapter_head', 'Head of Local Chapter'), ('member', 'End User / Member'), ('visitor', 'Visitor'), ('pee_member', 'Private Equity Exchange Member')], default='visitor', max_length=32)),
                ('background', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
                ('iq_score', models.FloatField(blank=True, null=True)),
                ('eq_score', models.FloatField(blank=True, null=True)),
                ('gq_score', models.FloatField(blank=True, null=True)),
                ('net_worth', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(max_length=32)),
                ('background', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
                ('iq_score', models.FloatField(blank=True, null=True)),
                ('eq_score', models.FloatField(blank=True, null=True)),
                ('gq_score', models.FloatField(blank=True, null=True)),
                ('net_worth', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('snapshot_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounts.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='AccessLevel',
        ),
    ]
