# Generated by Django 5.2.8 on 2025-12-01 15:56

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_username_validator'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.EmailUserManager()),
            ],
        ),
    ]
