# Generated by Django 5.2.8 on 2025-12-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_verificationcode_email_alter_verificationcode_user_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='verificationcode',
            name='accounts_ve_user_id_1bdc10_idx',
        ),
        migrations.RemoveIndex(
            model_name='verificationcode',
            name='accounts_ve_email_8a6b1f_idx',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='signup_access_level',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='signup_password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='signup_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
