# Generated by Django 5.2.8 on 2025-12-17 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('company_name', models.CharField(max_length=512)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('raw_payload', models.JSONField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'source_id'], name='msp_rawfirm_source_f6a9c8_idx'), models.Index(fields=['company_name'], name='msp_rawfirm_company_cee4f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('matched_rules', models.JSONField(blank=True, default=list)),
                ('is_us', models.BooleanField(default=False)),
                ('suspected_msp', models.BooleanField(default=False)),
                ('suspected_pe', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_firm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='msp.rawfirm')),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedMSPFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.IntegerField(default=3)),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verified', to='msp.candidatefirm')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_method', models.CharField(choices=[('call', 'Call'), ('email', 'Email')], default='call', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('no_answer', 'No Answer'), ('not_msp', 'Not MSP'), ('not_pe', 'Not PE'), ('confirmed', 'Confirmed'), ('invalid_contact', 'Invalid Contact')], max_length=32, null=True)),
                ('notes', models.TextField(blank=True)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('caller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='msp.candidatefirm')),
            ],
            options={
                'indexes': [models.Index(fields=['candidate', 'called_at'], name='msp_callver_candida_ff9cfa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='candidatefirm',
            index=models.Index(fields=['status', 'score'], name='msp_candida_status_3762e6_idx'),
        ),
        migrations.AddIndex(
            model_name='verifiedmspfirm',
            index=models.Index(fields=['verified_at'], name='msp_verifie_verifie_628421_idx'),
        ),
    ]
