# Generated by Django 5.2.8 on 2025-12-17 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatefirm',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatefirm',
            name='last_called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatefirm',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatefirm',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='candidatefirm',
            index=models.Index(fields=['assigned_to'], name='msp_candida_assigne_fa2691_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatefirm',
            index=models.Index(fields=['locked_at'], name='msp_candida_locked__65207b_idx'),
        ),
    ]
