# Generated by Django 5.2.8 on 2025-11-18 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('template', models.CharField(default='default', help_text="Frontend template/layout key, e.g. 'landing', 'article', etc.", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('access_levels', models.ManyToManyField(blank=True, help_text='If empty, public. If set, only visible to those levels.', related_name='pages', to='accounts.accesslevel')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Logical key, e.g. 'hero.title' or 'section1.body'.", max_length=255)),
                ('language', models.CharField(default='en', help_text="Language code, e.g. 'en', 'ur'.", max_length=10)),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('markdown', 'Markdown'), ('html', 'HTML'), ('json', 'JSON')], default='text', max_length=20)),
                ('value', models.JSONField(blank=True, help_text="For text: {'text': '...'}, for rich structures, use JSON.", null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='content.page')),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
                'ordering': ['page', 'sort_order', 'key'],
                'unique_together': {('page', 'key', 'language')},
            },
        ),
    ]
