# Generated by Django 5.2.8 on 2025-11-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='access_levels',
        ),
        migrations.AddField(
            model_name='page',
            name='access_level',
            field=models.CharField(blank=True, choices=[('owner', 'Owner & Super Administrator'), ('developer', 'Developer / Programmer'), ('admin', 'Administrator'), ('chapter_head', 'Head of Local Chapter'), ('member', 'End User / Member'), ('visitor', 'Visitor'), ('pee_member', 'Private Equity Exchange Member')], help_text="If empty, public page. If set, only visible to that access level and above (we'll enforce in API).", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
