# Generated by Django 5.2.8 on 2025-11-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_page_access_levels_page_access_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Text'), ('markdown', 'Markdown'), ('html', 'HTML'), ('json', 'JSON'), ('image', 'Image'), ('list', 'List')], default='text', max_length=20),
        ),
    ]
