# Generated by Django 5.2.8 on 2025-12-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_contentblock_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image for this block when block_type = image.', null=True, upload_to='content/blocks/'),
        ),
    ]
