# Generated by Django 5.2.8 on 2025-11-18 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_key', models.CharField(help_text="Translation key, e.g. 'menu.about.mission' (NO hardcoded text).", max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Optionally used to map to a content page slug.', max_length=255)),
                ('path', models.CharField(blank=True, help_text="Route or external URL, e.g. '/about' or 'https://emmafoundation.net'.", max_length=512)),
                ('position', models.CharField(choices=[('top', 'Top'), ('main', 'Main'), ('footer', 'Footer')], default='main', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('access_levels', models.ManyToManyField(blank=True, help_text='If empty, visible to everyone (visitor). If set, only visible to those levels.', related_name='menu_items', to='accounts.accesslevel')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['position', 'order'],
            },
        ),
    ]
