# Generated by Django 5.2.8 on 2025-11-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='access_levels',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='access_level',
            field=models.CharField(blank=True, choices=[('owner', 'Owner & Super Administrator'), ('developer', 'Developer / Programmer'), ('admin', 'Administrator'), ('chapter_head', 'Head of Local Chapter'), ('member', 'End User / Member'), ('visitor', 'Visitor'), ('pee_member', 'Private Equity Exchange Member')], help_text='If empty: visible to everyone. Else: restricted.', max_length=32, null=True),
        ),
    ]
